# Generated by Django 5.0.6 on 2024-05-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp', '0003_alter_patient_address_alter_patient_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='disease',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
