# Generated by Django 5.0.6 on 2024-05-24 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosp', '0004_appointment_disease'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='patient',
            new_name='Patient',
        ),
    ]
